### ISSUE TITLE
Error in writing data to Cassandra from Storm

### ISSUE THREAD

**Issue by jenamrinal** [hmsonline/storm-cassandra#54]
I am working on a project that involves Kafka-Storm-Cassandra. I am receiving the below error. Any thought on this?

2015-03-19 13:09:05 c.n.a.c.i.Slf4jConnectionPoolMonitorImpl [INFO] TransportException: [host=xxx.xx.xx.xxx(xxx.xx.xx.xxx):9160, latency=1002(0), attempts=0]org.apache.thrift.transport.TTransportException: java.net.NoRouteToHostException: No route to host
2015-03-19 13:09:06 c.n.a.c.i.Slf4jConnectionPoolMonitorImpl [WARN] PoolTimeoutException: [host=xxx.xx.xx.xxx(xxx.xx.xx.xxx):9160, latency=2001(2001), attempts=1]Timed out waiting for connection
2015-03-19 13:09:06 c.h.s.c.c.AstyanaxClient [WARN] Astyanax initialization failed.
com.netflix.astyanax.connectionpool.exceptions.PoolTimeoutException: PoolTimeoutException: [host=xxx.xx.xx.xxx(xxx.xx.xx.xxx):9160, latency=2001(2001), attempts=1]Timed out waiting for connection
    at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.waitForConnection(SimpleHostConnectionPool.java:218) ~[stormjar.jar:na]
    at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:185) ~[stormjar.jar:na]
    at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:66) ~[stormjar.jar:na]
    at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:67) ~[stormjar.jar:na]
    at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:253) ~[stormjar.jar:na]
    at com.netflix.astyanax.thrift.ThriftKeyspaceImpl.executeOperation(ThriftKeyspaceImpl.java:464) ~[stormjar.jar:na]
    at com.netflix.astyanax.thrift.ThriftKeyspaceImpl.describeKeyspace(ThriftKeyspaceImpl.java:216) ~[stormjar.jar:na]
    at com.hmsonline.storm.cassandra.client.AstyanaxClient.start(AstyanaxClient.java:144) ~[stormjar.jar:na]
    at com.hmsonline.storm.cassandra.bolt.CassandraBolt.prepare(CassandraBolt.java:43) [stormjar.jar:na]
    at com.hmsonline.storm.cassandra.bolt.AbstractBatchingBolt.prepare(AbstractBatchingBolt.java:56) [stormjar.jar:na]
    at backtype.storm.daemon.executor$fn__5697$fn__5710.invoke(executor.clj:732) [storm-core-0.9.3.2.2.0.0-2041.jar:0.9.3.2.2.0.0-2041]
    at backtype.storm.util$async_loop$fn__452.invoke(util.clj:463) [storm-core-0.9.3.2.2.0.0-2041.jar:0.9.3.2.2.0.0-2041]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
2015-03-19 13:09:06 b.s.util [ERROR] Async loop died!
java.lang.IllegalStateException: Failed to prepare Astyanax
    at com.hmsonline.storm.cassandra.client.AstyanaxClient.start(AstyanaxClient.java:148) ~[stormjar.jar:na]
    at com.hmsonline.storm.cassandra.bolt.CassandraBolt.prepare(CassandraBolt.java:43) ~[stormjar.jar:na]
    at com.hmsonline.storm.cassandra.bolt.AbstractBatchingBolt.prepare(AbstractBatchingBolt.java:56) ~[stormjar.jar:na]
    at backtype.storm.daemon.executor$fn__5697$fn__5710.invoke(executor.clj:732) ~[storm-core-0.9.3.2.2.0.0-2041.jar:0.9.3.2.2.0.0-2041]
    at backtype.storm.util$async_loop$fn__452.invoke(util.clj:463) ~[storm-core-0.9.3.2.2.0.0-2041.jar:0.9.3.2.2.0.0-2041]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]

**Comment by boneill42** [comment]
It is having trouble connected to Cassandra.  Do you have the host configuration set properly?

Also - you may want to switch over to storm-cassandral-cql.  (the CQL version of this driver)
We are no longer actively developing storm-cassandra.

**Comment by jenamrinal** [comment]
Link to get storm-cassandral-cql?

**Comment by boneill42** [comment]
https://github.com/hmsonline/storm-cassandra-cql
